language: node_js
node_js:
    - "0.10"
    - "0.8"

before_script:
    - bower install
script:
    - ./node_modules/karma/bin/karma start ./karma.conf.js --single-run --browsers PhantomJS --reporters=dots
